# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.5
group=net.anweisen
java_version=25
# Common
minecraft_version=26.3
mod_name=NotEnoughPots
mod_author=anweisen
mod_id=notenoughpots
license=All-Rights-Reserved
credits=
description=Put all your crops into flower pots
minecraft_version_range=[26.3, 26.4)
minecraft_version_range_fabric=>=26.3 <26.4
# 26.1 is deobfuscated, parchment is no longer required (official parameter names are shipped by mojang)
neo_form_version=26.3-1
# Fabric
fabric_loader_version=0.19.5
fabric_version=0.161.0+26.3
# Forge
forge_version=66.0.2
forge_loader_version_range=[66,)
# NeoForge
neoforge_version=26.3.0.7-beta
# the javafml language loader version, this is the version of FancyModLoader neoforge bundles (12.x for 26.3+)
neoforge_loader_version_range=[12,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
