package net.anweisen.notenoughpots;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import java.util.Locale;

/**
 * @author anweisen | https://github.com/anweisen
 * @since 1.0
 */
public enum NotEnoughPotsBlockType implements IPottedBlockType {

  POTTED_SUGAR_CANE(Blocks.SUGAR_CANE),
  POTTED_SUNFLOWER(Blocks.SUNFLOWER),
  POTTED_ROSE_BUSH(Blocks.ROSE_BUSH),
  POTTED_PEONY(Blocks.PEONY),
  POTTED_LILAC(Blocks.LILAC),
  POTTED_LARGE_FERN(Blocks.LARGE_FERN),
  POTTED_MELON_STEM(Blocks.MELON_STEM),
  POTTED_PUMPKIN_STEM(Blocks.PUMPKIN_STEM),
  POTTED_SHORT_GRASS(Blocks.SHORT_GRASS),
  POTTED_TALL_GRASS(Blocks.TALL_GRASS),
  POTTED_WHEAT(Blocks.WHEAT),
  POTTED_CARROTS(Blocks.CARROTS),
  POTTED_POTATOES(Blocks.POTATOES),
  POTTED_BEETROOTS(Blocks.BEETROOTS),
  POTTED_MELON_BLOCK(Blocks.MELON),
  POTTED_PUMPKIN_BLOCK(Blocks.PUMPKIN),
  POTTED_CHORUS_FLOWER(Blocks.CHORUS_FLOWER),
  POTTED_CHORUS_PLANT(Blocks.CHORUS_PLANT),
  POTTED_NETHER_WART(Blocks.NETHER_WART),
  POTTED_COCOA(Blocks.COCOA),
  POTTED_VINE(Blocks.VINE),
  POTTED_RED_MUSHROOM_BLOCK(Blocks.RED_MUSHROOM_BLOCK),
  POTTED_BROWN_MUSHROOM_BLOCK(Blocks.BROWN_MUSHROOM_BLOCK),
  POTTED_MUSHROOM_STEM(Blocks.MUSHROOM_STEM),
  POTTED_OAK_LEAVES(Blocks.OAK_LEAVES),
  POTTED_SPRUCE_LEAVES(Blocks.SPRUCE_LEAVES),
  POTTED_BIRCH_LEAVES(Blocks.BIRCH_LEAVES),
  POTTED_JUNGLE_LEAVES(Blocks.JUNGLE_LEAVES),
  POTTED_ACACIA_LEAVES(Blocks.ACACIA_LEAVES),
  POTTED_DARK_OAK_LEAVES(Blocks.DARK_OAK_LEAVES),
  POTTED_NETHER_WART_BLOCK(Blocks.NETHER_WART_BLOCK),
  POTTED_HAY_BLOCK(Blocks.HAY_BLOCK),
  POTTED_CARVED_PUMPKIN(Blocks.CARVED_PUMPKIN),
  POTTED_JACK_O_LANTERN(Blocks.JACK_O_LANTERN),
  // 1.13+
  POTTED_SEA_PICKLE(Blocks.SEA_PICKLE),
  POTTED_KELP(Blocks.KELP),
  POTTED_SEAGRASS(Blocks.SEAGRASS),
  POTTED_TUBE_CORAL(Blocks.TUBE_CORAL),
  POTTED_BRAIN_CORAL(Blocks.BRAIN_CORAL),
  POTTED_BUBBLE_CORAL(Blocks.BUBBLE_CORAL),
  POTTED_FIRE_CORAL(Blocks.FIRE_CORAL),
  POTTED_HORN_CORAL(Blocks.HORN_CORAL),
  POTTED_DEAD_TUBE_CORAL(Blocks.DEAD_TUBE_CORAL),
  POTTED_DEAD_BRAIN_CORAL(Blocks.DEAD_BRAIN_CORAL),
  POTTED_DEAD_BUBBLE_CORAL(Blocks.DEAD_BUBBLE_CORAL),
  POTTED_DEAD_FIRE_CORAL(Blocks.DEAD_FIRE_CORAL),
  POTTED_DEAD_HORN_CORAL(Blocks.DEAD_HORN_CORAL),
  POTTED_TUBE_CORAL_FAN(Blocks.TUBE_CORAL_FAN),
  POTTED_BRAIN_CORAL_FAN(Blocks.BRAIN_CORAL_FAN),
  POTTED_BUBBLE_CORAL_FAN(Blocks.BUBBLE_CORAL_FAN),
  POTTED_HORN_CORAL_FAN(Blocks.HORN_CORAL_FAN),
  POTTED_FIRE_CORAL_FAN(Blocks.FIRE_CORAL_FAN),
  POTTED_DEAD_TUBE_CORAL_FAN(Blocks.DEAD_TUBE_CORAL_FAN),
  POTTED_DEAD_BRAIN_CORAL_FAN(Blocks.DEAD_BRAIN_CORAL_FAN),
  POTTED_DEAD_BUBBLE_CORAL_FAN(Blocks.DEAD_BUBBLE_CORAL_FAN),
  POTTED_DEAD_HORN_CORAL_FAN(Blocks.DEAD_HORN_CORAL_FAN),
  POTTED_DEAD_FIRE_CORAL_FAN(Blocks.DEAD_FIRE_CORAL_FAN),
  POTTED_TUBE_CORAL_BLOCK(Blocks.TUBE_CORAL_BLOCK),
  POTTED_BRAIN_CORAL_BLOCK(Blocks.BRAIN_CORAL_BLOCK),
  POTTED_BUBBLE_CORAL_BLOCK(Blocks.BUBBLE_CORAL_BLOCK),
  POTTED_FIRE_CORAL_BLOCK(Blocks.FIRE_CORAL_BLOCK),
  POTTED_HORN_CORAL_BLOCK(Blocks.HORN_CORAL_BLOCK),
  POTTED_DEAD_TUBE_CORAL_BLOCK(Blocks.DEAD_TUBE_CORAL_BLOCK),
  POTTED_DEAD_BRAIN_CORAL_BLOCK(Blocks.DEAD_BRAIN_CORAL_BLOCK),
  POTTED_DEAD_BUBBLE_CORAL_BLOCK(Blocks.DEAD_BUBBLE_CORAL_BLOCK),
  POTTED_DEAD_FIRE_CORAL_BLOCK(Blocks.DEAD_FIRE_CORAL_BLOCK),
  POTTED_DEAD_HORN_CORAL_BLOCK(Blocks.DEAD_HORN_CORAL_BLOCK),
  // 1.14+
  POTTED_SWEET_BERRY_BUSH(Blocks.SWEET_BERRY_BUSH),
  // 1.16+
  POTTED_TWISTING_VINES(Blocks.TWISTING_VINES),
  POTTED_WEEPING_VINES(Blocks.WEEPING_VINES),
  POTTED_NETHER_SPROUTS(Blocks.NETHER_SPROUTS),
  POTTED_WARPED_WART_BLOCK(Blocks.WARPED_WART_BLOCK),
  // 1.17+
  POTTED_CAVE_VINES(Blocks.CAVE_VINES), // (Glow Berries)
  POTTED_HANGING_ROOTS(Blocks.HANGING_ROOTS),
  POTTED_SPORE_BLOSSOM(Blocks.SPORE_BLOSSOM), // 1.18?
  POTTED_SMALL_DRIPLEAF(Blocks.SMALL_DRIPLEAF),
  POTTED_BIG_DRIPLEAF(Blocks.BIG_DRIPLEAF),
  POTTED_AZALEA_LEAVES(Blocks.AZALEA_LEAVES),
  POTTED_FLOWERING_AZALEA_LEAVES(Blocks.FLOWERING_AZALEA_LEAVES),
  // 1.19+
  POTTED_SCULK_VEIN(Blocks.SCULK_VEIN),
  POTTED_MANGROVE_LEAVES(Blocks.MANGROVE_LEAVES),
  // 1.20+
  POTTED_PINK_PETALS(Blocks.PINK_PETALS),
  POTTED_PITCHER_PLANT(Blocks.PITCHER_PLANT),
  POTTED_PITCHER_CROP(Blocks.PITCHER_CROP),
  POTTED_TORCHFLOWER_SEEDS(Blocks.TORCHFLOWER_CROP),
  POTTED_CHERRY_LEAVES(Blocks.CHERRY_LEAVES),
  ;

  private final String name;
  private final Block flower;

  NotEnoughPotsBlockType(Block flower) {
    this.flower = flower;
    // using Locale.ROOT fixes https://github.com/anweisemods/NotEnoughPots/issues/4
    this.name = this.name().toLowerCase(Locale.ROOT);
  }

  @Override
  public Block getFlowerBlock() {
    return this.flower;
  }

  @Override
  public String getName() {
    return this.name;
  }

  public Block findBlock() {
    return NotEnoughPotsCommons.getBridge().getPottedBlock(this);
  }

}
